# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f9efa0b21a9beb347a5db4ce12e99f47d299f72cda14c7828a17abb14325b6373e8014feaac94e449a68ead127c146cd5e3a242e6fe4037dd2938a41d7282df

test:
  secret_key_base: d25874d68a882f82efce4f9ce1d594ac48014bc1b114e61d432594139ffc2d65d36a08fd2c399bfb591e9e1b44007ab824598df32c6f21cdf8ee5723bae1c59f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
